### ISSUE TITLE
Allow versions for external plugins

### ISSUE THREAD

**Issue by nrb** [bigjust/ansible-helga#5]
When installing my custom plugin, I want to always grab the latest version. However, right now, as long as there is _a_ version installed, Ansible's pip module is happy.

I'd like to figure out a way to optionally specify versions per plugin. This might not be possible without modifying Ansible module code, though, since when you give the `version` arg to the pip module, it always expects that variable to be something other than `null`.

I've played around with a few scenarios by adding different steps, but so far it looks like I'm duplicating work by installing the package more than once.

I'll also investigate whether this is a thing you can do with other Ansible package management modules.

**Comment by nrb** [comment]
So it looks like you can specify `state=latest` to get the latest version of a package. However, as this role is written now, making that change would mean _all_ plugins would be set to use the latest.

I'm not sure if this is acceptable or not for the role. For me, it would be since I'm really only installing 1 package. My guess is that for a general purpose role, it's not.

**Comment by bigjust** [comment]
I see no reason why we can't add an optional `state` field on the helga_external_plugins structure and default to `present`

**Comment by nrb** [comment]
Yeah, that's probably the best way to approach it. I can get a PR in soon.
